### ISSUE TITLE
ms code to recreate analysis from biorxiv paper

### ISSUE THREAD

**Issue by stsmall** [champost/ABLE#16]
Hi,
I am using ABLE on my study organism but am getting, what I would consider, non-biologically realistic parameter estimates. I would like to test my understanding by replicating the Orangutan point estimates from the biorxiv paper. I installed and downloaded ABLE and while I find the input files for 2kb and 500bp in the /data, I am uncertain how to match the config files to do the task infer. Would you be willing to share those here or make them a part of the /data example?

Also, when converting from pseudo-ms to bSFS, what is the purpose of the file "block_SNPs.txt"? It is created regardless of the output file name passed when converting. 

thank you,
scott

**Comment by amin-saffari** [comment]
Hi @stsmall ,

As It points out at the ABLE manual (Page 6 section datafile_format pseudo_MS), the file named block_SNPs.txt is created with the number of SNPs per sequence block providing for a manual cross-check that \ABLE\ has correctly accounted for available polymorphism. While tri/quadri-allelic nucleotide positions are ignored they are however listed in block_SNPs.txt.
Concerning the config file, I think the one in section 4.4.3 of ABLE manual should be it!

**Comment by stsmall** [comment]
Hi @amin-saffari,
Sorry about that. You are absolutely right about the block_SNPs.txt being in the manual. 
The ms command in 4.4.3 (page 18) refers to the Figure 1 examples in section 4.4 (Fig3 in biorxiv paper). Is there an example output file or something so I can compare against my estimates with that same data and command?
thank you!

**Comment by champost** [comment]
Refer to the [ABLE Google groups](https://groups.google.com/d/msg/groupABLE/zIExAvcI_lk/XAJ64KJaAgAJ) answer.
