### ISSUE TITLE
Increase precision of output estimates

### ISSUE THREAD

**Issue by stsmall** [champost/ABLE#17]
Hi,
Thanks for a great program. I am using some fairly small numbers to test some different nested models. Is there an option to increase the output precision of the parameter estimates?
thank you,
stsmall

**Comment by champost** [comment]
Hi Scott,
Not really but I could add that quite quickly.
Stay tuned,
Champak

**Comment by champost** [comment]
@stsmall With the latest commit, you should now be able to specify the output precision with the `output_precision` keyword followed by an integer of your choice in the config file (still need to update the doc though). 
Enjoy!
Champak
