### ISSUE TITLE
Joint bSFS from a single population

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [champost/ABLE#28]
Hi Champak,

I am interested in using ABLE for demographic and recombination rate inference given sampling of two diploid genomes from a single population.

The folded SFS for this sampling scheme is small (there are only two types of segregating sites - singletons/tripletons and doubletons). 

Additionally, the SFS here lumps together two different types of segregating sites as doubletons - those where both individuals are heterozygous and those where individuals are homozygous for different alleles. This doesn't matter for an SFS because the frequencies of these doubletons should be equal in a single panmictic population. However, for a bSFS it is surely preferable to record these different doubletons because if they appear in the same block then there has to have been a recombination event (i.e. there is a four gamete violation) and so they provide information about the recombination rate.

I think these different types of doubletons are recorded in a folded joint bSFS. I have tried to obtain the exact folded joint bSFS for a single population when at time 0 there is a split into two (arbitrary) populations. For simplicity, I used a very small theta value to mimic sampling a single site. 

`~/software/ABLE/ABLE 4 500000 -t 0.01 -I 2 2 2 -ej 0 1 2 -T config.txt`

Where `config.txt` contains

```
pops 2 2 2
kmax 4
folded
task exact_bSFS
bSFS exact_bSFS.txt
seed_PRNG 444
```

ABLE (cloned from git) finished with a segmentation fault, but does write the bSFS to file before this. Maybe the segmentation fault is nothing to worry about?

```
Setting up 64 threads...
Trees sampled : 500000
Time taken for computation : 4 seconds
Segmentation fault (core dumped)
```

Looking at the five most frequent entries in the bSFS, (1,0,0,0) and (0,0,1,0) seem to be entries where either diploid genome is heterozygous. The next two bSFS entries must be the two different types of doubletons, but I was surprised to see that they are at different frequencies. In fact, (0,0,0,1) is almost exactly double (0,1,0,0).

```
(0,0,0,0) : 9.601878e-01
(1,0,0,0) : 6.322578e-03
(0,0,1,0) : 6.361129e-03
(0,0,0,1) : 3.196020e-03
(0,1,0,0) : 1.612090e-03
```

I don't understand why this would be. Given no population structure wouldn't we expect these two doubleton types to be equal in frequency? Any ideas on why this is? Perhaps I am misunderstanding what they bSFS entries actually are.

Additionally, the frequencies in the bSFS sum to `0.973652`. Might this suggest that some entries are not being approximated correctly?

Any thoughts would be really appreciated. I also realise this is a very long issue, so I am happy to move to email instead if you like.

Best wishes,

Alex

**Comment by A-J-F-Mackintosh** [comment]
Hi again,

I did some more thinking about this and realised that that those entries in the bSFS actually do match the theoretical expectation - i.e.  (0,0,0,1) should be twice as frequent as (0,1,0,0). So please ignore that part of my original message.

I am still curious about why the frequency of exact bSFS entires do not sum to 1. Limited precision of floats?

Best,

Alex

**Comment by champost** [comment]
Hi Alex,

Thank for your interest in ABLE. Unfortunately, I do not have the bandwidth right now to follow-up promptly on questions regarding ABLE.

However, the segmentation and the sum of entries not summing to 1 is indeed surprising. Without trying to replicate your trial, I am wondering whether the "64 threads" which have been setup are the culprit. Here are some leads :
- limit the number of threads (say to 4 threads) with the `set_threads` option,
- increase `seed_PRNG` to an 8 digit number (I remember running into [some PRNG related issues](https://github.com/champost/ABLE/search?q=PRNG&type=commits) during development) and/or
- explore whether a population split later in time (e.g. `ej 0.5 1 2`) also leads to frequencies not adding up.

If needed, here is the actual command line (behind **Fig. 2b** and **Fig. 3** from [our published manuscript](https://doi.org/10.1186/s13059-018-1517-y)) for testing our ever-converging "_exact_" bSFS frequencies with the analytical bSFS using the original "_generating function_" method (by [Lohse _et al._, 2011](https://doi.org/10.1534/genetics.111.129569)) implemented in Mathematica : 

    ABLE 4 100000 -t 1 -I 2 2 2 -m 1 2 1 -ej 1.25 1 2 -T



Best,
Champak

**Comment by A-J-F-Mackintosh** [comment]
Hi Champak,

Thanks for getting back to me.

I followed your suggestions and it seems as though `set_threads 1` is needed to generate an exact bSFS where the frequencies sum to 1.

I still have the segmentation fault but all results are being written, so it is fine for doing some exploratory analyses.

Thanks again,

Alex
